version: "3"

services:
  auth: 
    build: ./
    container_name: "auth"
    image: auth
    depends_on:
      - delivery_db
    environment:
      - DB_HOST=delivery_db
      - PORT=8081
    ports:
      - 8081:8081
  delivery:
    container_name: "delivery"
    image: delivery
    depends_on:
      - delivery_db
    environment:
      - DB_HOST=delivery_db
      - AUTH_HOST=auth
      - PORT=4200
    ports:
      - 4200:4200
  delivery_db:
    image: postgres
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=delivery